### PR TITLE
Update configuration.en.md about password encryption strength

### PR DESCRIPTION
**Pull request by sona-tar**
I didn't find doc about salt.

I created doc in reference to the following pages.

- [パスワード暗号化について学びを得た](https://ten-snapon.com/archives/1399)
- [STNS pepabo_hatena_tech_con](https://speakerdeck.com/pyama86/stns-pepabo-hatena-tech-con?slide=17)

### CODE REVIEW

**Comment by sona-tar** [comment]
Not not supporting salt?

https://github.com/STNS/STNS/commit/09731d4dfe944ed32bb1e79c27af35c52fb1cf79

**Comment by sona-tar** [comment]
I find to following line. It looks only support sha512 and not support salt. Is it right?

https://github.com/STNS/stns-passwd/blob/9844e72d4b737faee9de3fc70652ef1acd1a1b93/cli.go#L71

**Comment by sona-tar** [comment]
If now not support salt, I'll close this PR.
Please reply.

**Comment by pyama86** [comment]
Hi!
I have changed password specifications in STNS 0.2.
https://ten-snapon.com/archives/1461

So this PR is closed.
thank you!

**Pull request closed without merging**
